### ISSUE TITLE
Make tables dynamic when drawing polygon after analysis

### ISSUE THREAD

**Issue by d4weed** [Vizzuality/gfw#1356]
In 

https://github.com/Vizzuality/gfw/blob/develop/app/assets/javascripts/map/presenters/AnalysisToolPresenter.js

The query to paint the geojson should take table name from layerspec

    'logging': 'http://wri-01.cartodb.com/api/v2/sql/?q=SELECT ST_AsGeoJSON(the_geom) from gfw_logging where cartodb_id ={0}',
    'mining':'http://wri-01.cartodb.com/api/v2/sql/?q=SELECT ST_AsGeoJSON(the_geom) from gfw_mining where cartodb_id ={0}',
    'oilpalm': 'http://wri-01.cartodb.com/api/v2/sql/?q=SELECT ST_AsGeoJSON(the_geom) from gfw_oil_palm where cartodb_id ={0}',
    'fiber': 'http://wri-01.cartodb.com/api/v2/sql/?q=SELECT ST_AsGeoJSON(the_geom) from gfw_wood_fiber where cartodb_id ={0}'

**Comment by apercas** [comment]
Fixed here: https://github.com/Vizzuality/gfw/commit/2847ac71dde2eb6efa8b6be6122e863849bcef4b

Deployed to PRO.
