### ISSUE TITLE
strange outlines appear around logos on page footer

### ISSUE THREAD

**Issue by robinkraft** [Vizzuality/gfw#2]
I've tried fixing this in the browser, but it seems to be a subtle issue - maybe a combination of an error in the sprite viewport definitions or some inherited CSS attributes? The fact that the outlines aren't rectangular is particularly strange.

![google chromescreensnapz122](https://f.cloud.github.com/assets/428784/1127256/88849898-1b35-11e3-9f75-43df8b42ddca.png)

**Comment by apercas** [comment]
I won't say anything, guys, hahaha
