### ISSUE TITLE
GLAD timeline play icon should change when clicking in timeline

### ISSUE THREAD

**Issue by matallo** [Vizzuality/gfw#2612]
**steps to reproduce**
- go to http://www.globalforestwatch.org/map/3/15.00/27.00/ALL/grayscale/umd_as_it_happens
- click play
- with the handle running, click in the timeline to move the handle to that point in the line

**expected behaviour**
- timeline to keep moving and icon remaining in "stop" OR
- timeline to stop and icon toggling to "play"

**actual behaviour**
- timeline stops and icon remain in "stop"

![gfw](https://cloud.githubusercontent.com/assets/36676/19186231/96c5851a-8c85-11e6-860d-9a6b01c3d886.gif)

**Comment by geriux** [comment]
Thanks @matallo ! We'll check it out.

**Comment by pjosh** [comment]
Hi @matallo ! We have fixed this strange behaviour. Thank you very much!

**Comment by matallo** [comment]
BOOM
