### ISSUE TITLE
Using google tiles in the application

### ISSUE THREAD

**Issue by prateek99** [Vizzuality/gfw#3840]
Is it legal to use google tiles without using google api?

Refer to 
https://cloud.google.com/maps-platform/terms/?hl=en#10-license-restrictions

**Comment by teresa-n-schofield** [comment]
Hello @prateek99 , thank you for inquiring about this. We have reached out to Google, and they have verified that everything is in order. 

Please feel free to let us know if you ever have any questions/feedback!

Best,

Teresa Schofield
Junior Product Specialist
Global Forest Watch
