### ISSUE TITLE
Bug Report: When accessing a Topics page directly from a URL the page crashes

### ISSUE THREAD

**Issue by simaob** [Vizzuality/gfw#4108]
Steps to reproduce:

1- Click link: http://www.globalforestwatch.org/topics/climate/#slides 
2- page breaks.

This doesn't happen if I visit the Topics page via the homepage.

I'm using Google Chrome.

Thanks! =)

**Comment by edbrett** [comment]
Hello there old friend! Thank you for flagging this, a fix has been deployed and you should see the page working again now 🚢 . There was an issue with a recent update to new breakpoints for responsive layouts. See fd5308a79353d3c18bdda8a1df785889fc0764db

**Comment by simaob** [comment]
I missed your notification, given I'm not on slack anymore 😭 . But great that it was fixed! Great job!
Take care!
