### ISSUE TITLE
support Infoamazonia stories alongside Mongabay

### ISSUE THREAD

**Issue by robinkraft** [Vizzuality/gfw#595]
This [Infoamazonia sync table](https://wri-01.cartodb.com/tables/table_6434519437/) contains the stories, with the same schema as the mongabay table [`mongabaydb`](https://wri-01.cartodb.com/tables/mongabaydb).

What's the best way to surface this on the GFW site? Just add Infoamazonia to the stories tab below mongabay?

**Comment by apercas** [comment]
Done.
